/**
 * Seeds the Grammar table with JLPT N5–N1 grammar patterns.
 * Data sourced from https://jlptgrammarlist.neocities.org/
 *
 * Skips patterns that already exist in the database (matched by pattern string).
 *
 * Usage:
 *   npm run seed:jlpt-grammar
 */
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

interface JlptGrammar {
  pattern: string;
  meaning: string;
  example: string | null;
  translation: string | null;
  jlptLevel: string;
  source: string;
}

const JLPT_GRAMMAR: JlptGrammar[] = [
  // ── JLPT N5 ─────────────────────────────────────────────────────────────
  { pattern: "いちばん", meaning: "the most", example: "ここがいちばん面白い場面です。", translation: "This is the most interesting scene.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "が 1", meaning: "as for (identifies something)", example: "弟がいる。", translation: "There is a younger brother.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "が 2", meaning: "but; however", example: "難しいが、楽しい。", translation: "It is difficult but fun.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "か 1", meaning: "or (A or B; choice between 2 objects)", example: "ここかそこ。", translation: "Here or there?", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "か 2", meaning: "question particle", example: "雨ですか。", translation: "Is it rain?", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "がある", meaning: "there is (used for non-living things)", example: "川がある。", translation: "There is a river.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "がいる", meaning: "there is (used for living things)", example: "可愛い女の子がいる。", translation: "There is a cute girl.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "から 1", meaning: "because; since", example: "車で来ましたから。", translation: "Because I drove here by car.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "から 2", meaning: "from", example: "西からの風。", translation: "A wind from the west.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "くらい / ぐらい", meaning: "about; approximately", example: "東京まで、３０分くらいです。", translation: "It's about 30 minutes to Tokyo.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "けど / けれども", meaning: "but; although", example: "早く寝たけれども、まだ眠たいです。", translation: "I went to sleep early but I am still tired.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "する", meaning: "to do", example: "質問する。", translation: "To ask a question.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "だ / です", meaning: "there is; this is", example: "猫だ。猫です。", translation: "There is a cat.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "たい", meaning: "want to", example: "何食べたい？", translation: "What do you want to eat?", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "だけ", meaning: "only; just", example: "これは水だけだ。", translation: "This is just water.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "たことがある", meaning: "have done before", example: "高い肉を食べたことがある。", translation: "I have eaten expensive meat before.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "だろう 1", meaning: "probably", example: "ペンがあるだろう。", translation: "There is probably a pen.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "だろう 2", meaning: "isn't it?; right?", example: "ここがいいだろう。", translation: "Here is good, isn't it?", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "つもり", meaning: "plan to; intend to", example: "日本に行くつもりだ。", translation: "I intend to go to Japan.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "で 1", meaning: "at; in (place of action)", example: "バーで飲む。", translation: "I'll drink at/in a bar.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "で 2", meaning: "with; by (means)", example: "バスで帰る。", translation: "I'll go home by bus.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "ている", meaning: "is / are / am doing", example: "何をしている？", translation: "What are you doing?", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "てから", meaning: "after doing", example: "映画を見てから、帰ります。", translation: "After watching the movie, I will go home.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "てください", meaning: "please do…", example: "食べてください。", translation: "Please eat.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "でしょう 1", meaning: "probably", example: "雨でしょうね。", translation: "It will probably be rain, won't it?", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "でしょう 2", meaning: "isn't it?; right?", example: "いいでしょう。", translation: "It's good isn't it?", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "てはいけない", meaning: "must not; may not", example: "ここに来てはいけない。", translation: "You must not come here.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "てもいい", meaning: "is okay; is alright to", example: "狭くてもいい。", translation: "It's fine even if it is narrow.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "と 1", meaning: "and", example: "黒と白の猫。", translation: "Black and white cat.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "と 2", meaning: "with", example: "友達と見る。", translation: "Watch with a friend.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "な", meaning: "don't do (prohibition)", example: "泣くな。", translation: "Don't cry.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "ないでください", meaning: "please don't", example: "泣かないでください。", translation: "Please don't cry.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "なる", meaning: "to become", example: "病気になる。", translation: "To become sick.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "に / へ", meaning: "to (destination / direction)", example: "駅に行く。駅へ行く。", translation: "To go to the station.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "にいく", meaning: "to go, in order to do...", example: "エレベーターで５かいにいく。", translation: "To use the elevator to go to the fifth floor.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "にする", meaning: "to decide on", example: "この音楽にする。", translation: "To decide on this music.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "の 1", meaning: "of (indicates possession)", example: "私の犬です。", translation: "It's my dog.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "の 2", meaning: "(turns verbs into nouns)", example: "彼は走るのが速い。", translation: "He runs fast.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "のが下手", meaning: "to be bad at", example: "彼は漢字を書くのが下手。", translation: "He is bad at writing kanji.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "のが上手", meaning: "to be good at", example: "彼女は歌うのが上手。", translation: "She is good at singing.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "のが好き", meaning: "like / love doing", example: "犬と遊ぶのが好き。", translation: "I like playing with dogs.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "ので", meaning: "because of; the reason is that", example: "太いので、走るのは遅い。", translation: "Because I am fat, my running is slow.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "は", meaning: "as for (topic marker)", example: "これは何？", translation: "What is this?", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "ほうがいい 1", meaning: "it'd be better to", example: "靴を脱いだほうがいいです。", translation: "It's better that you take off your shoes.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "ほうがいい 2", meaning: "it'd be better not to", example: "そのことを言わないほうがいいかもしれない。", translation: "It might be better not to say such things.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "前に", meaning: "before", example: "犬が門の前にいる。", translation: "There is a dog in front of the gate.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "まだ", meaning: "still; not yet", example: "娘はまだ起きていません。", translation: "My daughter hasn't got up yet.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "まで", meaning: "until; till; to; even", example: "駅まで、歩く。", translation: "To walk until the station.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "も", meaning: "also; too; as well", example: "服も古い。", translation: "The clothes are also old.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "もう", meaning: "already; anymore", example: "もう帰った。", translation: "They already went home.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "や", meaning: "and (etc.)", example: "鳥や馬が山にいました。", translation: "Birds, horses, etc were in the mountains.", jlptLevel: "N5", source: "JLPT N5" },
  { pattern: "より○○のほうが○○", meaning: "is more ~ than", example: "飛行機より電車のほうが遅いです。", translation: "An aeroplane is slower than a train.", jlptLevel: "N5", source: "JLPT N5" },

  // ── JLPT N4 ─────────────────────────────────────────────────────────────
  { pattern: "後で", meaning: "after; later", example: "後で電話します。", translation: "I will call you later.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "あまり○○ない", meaning: "not very; not much", example: "あまり肉を食べない。", translation: "I don't eat very much meat.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "いたす", meaning: "to do (humble する)", example: "今確認いたします。", translation: "I will confirm it now. (humble)", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "いらっしゃる", meaning: "to be; to come; to go (honorific)", example: "ここにはよくいらっしゃるんですか？", translation: "Do you come here often?", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "お○○ください", meaning: "please do (honorific)", example: "お水をください。", translation: "Can I have some water, please?", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "お○○になる", meaning: "to do (honorific)", example: "お世話になりました。", translation: "Thank you for your kindness.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "おきに", meaning: "repeated at intervals; every", example: "一時間おきに電車があります。", translation: "There's a train every hour.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "終わる", meaning: "to finish; to end", example: "終わるまで、頑張った。", translation: "I gave my best until it finished.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "かい", meaning: "(turns a sentence into a yes/no question)", example: "今朝は飯を食べたかい？", translation: "Did you have a meal this morning?", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "かしら", meaning: "I wonder (feminine)", example: "裕子さんは大丈夫かしら。", translation: "I wonder if Yuko is okay.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "がする", meaning: "to smell; hear; taste (sensation)", example: "いい匂いがする。", translation: "It smells good.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "方", meaning: "way of; method of doing", example: "私の考え方。", translation: "My way of thinking.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "かどうか", meaning: "whether or not", example: "行くかどうか分からない。", translation: "I don't know whether I will go or not.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "かな", meaning: "I wonder (casual)", example: "外は寒いかな。", translation: "I wonder if it's cold outside.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "かもしれない", meaning: "might; maybe", example: "アレルギーかもしれないですね。", translation: "It could be allergies.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "がる", meaning: "to show signs of; to feel; to think", example: "怖がらないでください。", translation: "Please don't be afraid.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "急に", meaning: "suddenly", example: "猫が急に噛み付いた。", translation: "The cat bit me suddenly.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "ございます", meaning: "there is (honorific ある)", example: "ほかにご質問はございますか。", translation: "Do you have any other questions?", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "こと", meaning: "(turns verbs into nouns)", example: "これ見たことある？", translation: "Have you seen this?", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "ことができる", meaning: "can; be able to", example: "馬に乗ることができる。", translation: "I can ride a horse.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "ことにする", meaning: "to decide on", example: "家を買うことにした。", translation: "I decided to buy a house.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "ことになる", meaning: "will become; it has been decided that", example: "他人に知れるとまずいことになるわね。", translation: "It'll be a bad thing if others find out.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "ごろ", meaning: "around; about (time)", example: "３時ごろに作り終わる。", translation: "I will finish making it around three o'clock.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "さ", meaning: "(turns adjectives into nouns)", example: "このテーブルは丁度良い高さだ。", translation: "This table is the right height for me.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "させられる", meaning: "to be made to do something", example: "息子は退学させられた。", translation: "My son was expelled.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "させる", meaning: "to make/let somebody do something", example: "この美しい話はあなたを感動させるだろう。", translation: "This lovely story will move you.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "し", meaning: "and; moreover (listing reasons)", example: "怖かったし、悲しかった。", translation: "I was scared, and I was sad.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "しか○○ない", meaning: "only; nothing but", example: "四つしか椅子がない。", translation: "There are only four chairs.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "じゃないか", meaning: "isn't it", example: "いいじゃないか。", translation: "It's fine isn't it?", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "すぎる", meaning: "too much; excessively", example: "小さすぎる。", translation: "Too small.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "ぜんぜん", meaning: "(not) at all", example: "お金がぜんぜんない。", translation: "I don't have any money at all.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "そうだ 1", meaning: "I heard that; it is said that", example: "明日は気温が下がるそうだ。", translation: "I heard that the temperature will go down tomorrow.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "そうだ 2", meaning: "look like; appear; seem", example: "眠そうだね。", translation: "You look sleepy.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "そうに / そうな", meaning: "seem; look like", example: "あの時計は高そうに見える。", translation: "That watch looks expensive.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "それでも", meaning: "but still; and yet", example: "明日雨降るの？それでも海に行く。", translation: "It may rain tomorrow and yet I'll still go to the sea.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "そんなに", meaning: "so; so much; like that", example: "そんなに心配しないで。", translation: "Don't worry too much.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "たがる", meaning: "to want to (third person)", example: "彼は動物園に行きたがる。", translation: "He wants to go to the zoo.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "だけで", meaning: "just by", example: "この寒さだけで死ぬよ。", translation: "Just by this coldness you will die.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "出す", meaning: "to suddenly begin; to suddenly appear", example: "トムは急に泣き出した。", translation: "Tom suddenly started to cry.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "たところ", meaning: "just finished doing; was just doing", example: "なんか、そんな気がしていたところです。", translation: "I was just starting to get that feeling.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "たばかり", meaning: "just did; something just happened", example: "今朝、着いたばかりです。", translation: "I arrived here only this morning.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "たら", meaning: "if; after; when", example: "眠くなったら言ってね。", translation: "If you get sleepy, tell me.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "たらどう", meaning: "why don't you", example: "もっと勉強したらどうですか？", translation: "Why don't you study more?", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "たり○○たり", meaning: "do such things like", example: "掃除をしたり、洗濯したりした。", translation: "I did things like cleaning and doing the laundry.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "続ける", meaning: "to continue doing", example: "仕事を続けてください。", translation: "Please keep working.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "てあげる", meaning: "to do something for someone", example: "今回だけは許してあげる。", translation: "I'll forgive you just this once.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "てある", meaning: "something is/has been done", example: "顔に嘘って書いてあるよ。", translation: "You have \"lies\" written all over your face.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "ていく", meaning: "to go and do; to continue doing", example: "大丈夫！お弁当を持って行くから。", translation: "It's okay! Because I will take bento with me.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "ていただけませんか", meaning: "could you please", example: "窓を閉めていただけませんか？", translation: "Could you close the window please?", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "ているところ", meaning: "in the process of doing", example: "ボーナスの使い道を考えているところです。", translation: "I'm thinking about what I should use the bonus for.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "ておく / とく", meaning: "to do something in advance for later", example: "冷蔵庫でジュースを冷やしておく。", translation: "I keep juice cool in the fridge (for later).", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "てくる", meaning: "to come to; to become; to continue", example: "泣けてくるなあ。", translation: "That brings me to tears.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "てくれる", meaning: "to do something for someone (speaker's benefit)", example: "それ取ってくれる？", translation: "Can you give me that?", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "でございます", meaning: "there is; this is (honorific である)", example: "京都ホテルでございます。", translation: "This is the Kyoto Hotel.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "てしまう / ちゃう", meaning: "to do something regretfully; to do completely", example: "お酒を飲み過ぎると、眠くなってしまう。", translation: "Drinking too much alcohol makes me sleepy (unfortunately).", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "てすみません", meaning: "I'm sorry for", example: "遅れてすみません。", translation: "I'm sorry I'm late.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "てほしい", meaning: "I want you to; I need you to", example: "一緒に勉強してほしいです。", translation: "I want you to study together with me.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "てみる", meaning: "to try to", example: "今週末に野球をしてみる。", translation: "I am going to try playing baseball this weekend.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "ても", meaning: "even if; even though", example: "たとえ両親が反対しても私は行く。", translation: "I will go even if my parents are against it.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "でも", meaning: "or something (suggestion)", example: "お茶でもどう？", translation: "How about tea or something?", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "てもらう", meaning: "to get somebody to do something", example: "この仕事を手伝ってもらう。", translation: "I will get someone to help with this work.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "てよかった", meaning: "I'm glad that", example: "今日運動してよかった。", translation: "I'm glad that I exercised today.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "と", meaning: "if; when (conditional); and", example: "母と娘。", translation: "Mother and daughter.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "ということ", meaning: "(changes a sentence or phrase into a noun)", example: "私にパーティに来てほしくないということはわかります。", translation: "I know you don't want me to come to the party.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "と思う", meaning: "I think; you think", example: "食べようと思う。", translation: "I think I'll eat.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "とか○○とか", meaning: "among other things; such as", example: "青とか水色が好き。", translation: "I like colors such as blue and light blue.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "とき", meaning: "when; at the time", example: "散歩するときは音楽を聴く。", translation: "I listen to music when I take a walk.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "ところ", meaning: "about to; on the verge of", example: "今から帰るところです。", translation: "I am just about to go home.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "ないで", meaning: "without doing; don't", example: "泣かないで。", translation: "Don't cry.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "ながら", meaning: "while; during; as (simultaneous actions)", example: "掃除しながら、テレビを見ます。", translation: "I watch TV while doing cleaning.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "なくてはいけない / なくてはならない", meaning: "must do; have to do", example: "毎日学校に行かなくてはいけない。", translation: "I have to go to school every day.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "なくてもいい", meaning: "don't have to", example: "急がなくてもいいよ。", translation: "You don't have to hurry.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "なければいけない / なければならない", meaning: "must do; have to do", example: "もっと勉強しなければいけないと思った。", translation: "I thought that I must study more.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "なさい", meaning: "(order somebody to do something)", example: "勉強しなさい。", translation: "Study!", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "なさる", meaning: "to do (honorific する)", example: "お飲み物はどうなさいますか。", translation: "Would you like something to drink?", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "など", meaning: "such as; things like", example: "腰や背中などが痛い。", translation: "Things like my hips and back hurt (among others).", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "なら", meaning: "if; in case; as for", example: "君なら、できる。", translation: "If it's you, you can do it.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "にくい", meaning: "difficult to", example: "箸は使いにくいです。", translation: "Chopsticks are difficult to use.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "の中で", meaning: "in; among", example: "果物の中で何が一番好きですか。", translation: "What fruit do you like best?", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "のに 1", meaning: "although; in spite of; even though", example: "無理って言ったのにまだやるの？", translation: "Even though I said it was impossible, you're still going to do it?", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "のに 2", meaning: "in order to", example: "手紙が届くのに三日かかりました。", translation: "It took three days in order for the letter to arrive.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "のように / のような", meaning: "like; similar to", example: "お箸はこのように使います。", translation: "Chopsticks are used like this.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "ば", meaning: "if… then (provisional conditional)", example: "天気が良ければフジ山が見える。", translation: "If the weather is good, you can see Mt. Fuji.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "場合は", meaning: "in the event of", example: "なお、雨の場合は中止です。", translation: "Moreover, it will be canceled in the event of rain.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "ばかり 1", meaning: "only; nothing but", example: "彼女はいつも文句ばかり言う。", translation: "She does nothing but complain.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "始める", meaning: "to start; to begin to", example: "先生はクラスを始める。", translation: "The teacher starts class.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "はずがない", meaning: "cannot be; is not supposed to be", example: "彼なんかに出来るはずがない。", translation: "Someone like him could never do it.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "はずだ", meaning: "it must be; it should be", example: "もっと良い方法があるはずだ。", translation: "There must be a better way.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "必要", meaning: "need; necessary", example: "これは、必要ですか。", translation: "Is this necessary?", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "必要がある", meaning: "need to", example: "私たちは話す必要がある。", translation: "We need to talk.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "ほしい", meaning: "to want something; to be in need of", example: "君がほしい！", translation: "I want you!", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "までに", meaning: "by; by the time", example: "明日までに電話をください。", translation: "Please call by tomorrow.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "みたい", meaning: "like; similar to; resembling", example: "あの雲は鳥みたいだ。", translation: "That cloud looks like a bird.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "みたいに / みたいな", meaning: "like; similar to", example: "レモンみたいな黄色。", translation: "Lemon-like yellow.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "やすい", meaning: "easy to; likely to", example: "ケーキは作りやすい。", translation: "Cake is easy to make.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "ようだ", meaning: "it seems that; it appears that; it looks like", example: "誰か来たようだ。", translation: "It seems that someone has come.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "ようと思う", meaning: "I think I will", example: "今日は早めに寝ようと思う。", translation: "I think I'll go to bed early tonight.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "ように / ような", meaning: "as; like; just like", example: "お箸はこのように使います。", translation: "Chopsticks are used like this.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "ようにする", meaning: "to try to; to make sure that", example: "無駄にお金を使わないようにしている。", translation: "I'm trying not to waste money.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "ようになる", meaning: "to reach the point that; to come to", example: "泥を落としたら、なんと新品のようになった。", translation: "When I cleaned off the mud, they became like brand new!", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "よていだ", meaning: "plan to; intend to", example: "私は九月に行く予定です。", translation: "I'm planning to go there in September.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "より", meaning: "than", example: "日本より熱い。", translation: "It's hotter than Japan.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "らしい", meaning: "-like; -ish", example: "彼女は女らしい。", translation: "She's feminine.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "られる 1", meaning: "to be able to do something (potential)", example: "その魚は生で食べられる。", translation: "The fish can be eaten raw.", jlptLevel: "N4", source: "JLPT N4" },
  { pattern: "られる 2", meaning: "to do (by someone) (passive)", example: "若い人達に教えられた。", translation: "Taught by young people.", jlptLevel: "N4", source: "JLPT N4" },

  // ── JLPT N3 ─────────────────────────────────────────────────────────────
  { pattern: "あまり", meaning: "so much that", example: "あまりにうるさかったので耳を塞いだ。", translation: "It was too noisy, so I covered my ears.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "あまりに", meaning: "too; excessively", example: "あまりにうるさかったので耳を塞いだわ。", translation: "It was too noisy, so I covered my ears.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "いくら○○ても", meaning: "no matter how", example: "いくら呼んでも彼は返事をしなかったわ。", translation: "No matter how many times I called, he didn't respond.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "一方だ", meaning: "continue to; more and more", example: "雨はひどくなる一方だ。", translation: "The rain is getting heavier and heavier.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "一方で", meaning: "on one hand; on the other hand", example: "父は自分に厳しい一方で、他人には優しい。", translation: "My father is strict with himself but kind to others.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "うちに", meaning: "while; before; during", example: "母はまだ暗いうちに起きる。", translation: "My mother gets up while it's still dark.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "おかげで", meaning: "thanks to; because of", example: "先生のおかげで大学に合格できました。", translation: "Thanks to the teacher, I passed the university exam.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "おそらく", meaning: "perhaps; likely; probably", example: "おそらく私のコンピューターには何百万枚もの写真が入っています。", translation: "I probably have millions of pictures on my computer.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "かけ", meaning: "half-finished; not yet completed", example: "テーブルの上に食べかけのケーキが置いてある。", translation: "The half-eaten cake is on the table.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "がたい", meaning: "hard to; difficult to", example: "信じがたい話だ。", translation: "It's a hard-to-believe story.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "がち", meaning: "apt to do; tend to do", example: "急ぐととかく失敗しがちだ。", translation: "If you hurry you tend to make mistakes.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "代わりに", meaning: "instead of; in exchange for", example: "手紙の代わりにメールをする。", translation: "I send an email instead of a letter.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "ぎみ", meaning: "-like; showing slight signs of", example: "風邪気味だったので薬を飲ませた。", translation: "I had a slight cold so I took medicine.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "きり", meaning: "only; just", example: "私達は二人きりになった。", translation: "The two of us were left alone.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "きる", meaning: "do something completely", example: "何せ朝から晩迄働いて疲れきっているんだ。", translation: "I'm tired out from working from morning till night.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "切れない", meaning: "being too much to finish", example: "銀河には数え切れないほど星がある。", translation: "There are too many stars to count in the Milky Way.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "くせに", meaning: "even though; and yet; despite", example: "この部屋は狭いくせに家賃がすごく高い。", translation: "Despite being small, the rent is very expensive.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "決して○○ない", meaning: "never; by no means", example: "トムは決して笑わない。", translation: "Tom never laughs.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "こそ", meaning: "certainly; emphasizes previous word", example: "今年こそダイエットをする。", translation: "I'll certainly go on a diet this year.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "ことか", meaning: "how; what (exclamatory)", example: "何度警告したことか。", translation: "How many times have I warned you?", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "ことがある", meaning: "can; sometimes happens", example: "小さい問題が大きい問題になることがある。", translation: "Small problems can become big problems.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "ことだ", meaning: "should; give advice", example: "同じ過ちを繰り返さないことだ。", translation: "You should not repeat the same mistake.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "ことに", meaning: "-ly; fortunately/unfortunately", example: "兄は交通事故に遭ったが、幸いなことに、軽いけがで済んだ。", translation: "My brother had an accident but fortunately only slightly injured.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "ことはない", meaning: "no need to; never happens", example: "あなたが心配することはないよ。", translation: "You don't have to worry about it.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "さえ", meaning: "even", example: "それは子供でさえ分かる。", translation: "Even children can understand it.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "さえ○○ば", meaning: "if only then", example: "薬を飲みさえすれば治ります。", translation: "If you drink your medicine you'll get better.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "しかない", meaning: "have no choice but", example: "今やるしかない。", translation: "Have no choice but to do it now.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "ずに", meaning: "without doing", example: "彼は何も言わずに去ってしまった。", translation: "He left without saying anything.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "ずにはいられない", meaning: "can't help but; unable to resist", example: "タツヤを気の毒に思わずにはいられなかったのだ。", translation: "I couldn't help feeling sorry for Tatsuya.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "せいで", meaning: "because of (negative cause)", example: "事故のせいで遅刻した。", translation: "I was late because of an accident.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "そうもない", meaning: "very unlikely to", example: "我々にはとけそうもない謎さ。", translation: "A mystery we're not likely to solve.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "その結果", meaning: "as a result", example: "その結果、無罪となっていた。", translation: "As a result, he had been acquitted.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "だけ", meaning: "as much as; to the extent that", example: "できるだけ、日本語を話すようにしよう。", translation: "As much as possible, try to speak Japanese.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "た結果", meaning: "as a result of", example: "よく話し合った結果、やはり離婚ということになりました。", translation: "As a result of discussion, we decided to divorce.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "だけど", meaning: "but; however (casual)", example: "飲み物だけど、辛い。", translation: "It is a drink, but it is spicy.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "確かに", meaning: "surely; certainly", example: "確かに、そうですね。", translation: "That's certainly so, isn't it?", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "たとえ○○ても", meaning: "even if the case", example: "たとえ、嵐になっても絶対に行く。", translation: "Even if a storm comes, I'll go for sure.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "たとえば", meaning: "for example", example: "たとえば、茎を曲げたり、方向を変えたりできます。", translation: "For example, they can bend their stems and change direction.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "たとたん", meaning: "as soon as; just now", example: "立ち上がったとたんに、目まいがした。", translation: "As soon as I stood up, I felt dizzy.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "たびに", meaning: "every time; whenever", example: "この本を読むたびに、彼のことを思い出す。", translation: "I think about him every time I read this book.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "ために 1", meaning: "for the sake of; in order to", example: "誰かのために料理する。", translation: "Cook for someone.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "ために 2", meaning: "because of; as a result of", example: "霧のために列車がおくれてしまった。", translation: "As a result of fog, the train was delayed.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "たらいい", meaning: "should; I hope; it would be nice if", example: "これ何分チンしたらいい？", translation: "How long should I microwave this?", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "だらけ", meaning: "covered all over; full of", example: "靴が泥だらけになったよ。", translation: "My shoes were covered in mud.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "ついでに", meaning: "taking the opportunity; while at it", example: "郵便局へ行ったついでに、葉書を買ってきた。", translation: "Since I was at the post office, I bought a postcard.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "っけ", meaning: "what is … again?", example: "ごめん、名前何だっけ？", translation: "Sorry, what is your name again?", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "っぱなし", meaning: "leaving something still in use", example: "窓を開けっぱなしで出かけた。", translation: "I left the windows open and went out.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "っぽい", meaning: "-ish; -like", example: "そのシャツは安っぽいね。", translation: "That shirt looks cheap doesn't it.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "つまり", meaning: "in other words; that is to say", example: "つまり、あなたは何も知らないのですね。", translation: "In other words, you don't know anything right?", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "てごらん", meaning: "please try to; please look", example: "絵を逆さにして見てごらん。", translation: "Try looking at the picture upside down.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "て初めて", meaning: "not until; only after", example: "生まれて初めて布団を敷いた。", translation: "I laid out the futon for the first time in my life.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "てもかまわない", meaning: "no problem; don't mind if", example: "ドアを閉めてもかまいませんか？", translation: "Do you mind if I close the door?", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "という", meaning: "called; named", example: "これは何という花ですか？", translation: "What is this flower called?", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "というと", meaning: "speaking of; when you say", example: "今日では、ブラウスというと女性用のシャツの事を指す。", translation: "Nowadays, a blouse usually refers to a women's shirt.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "というのは", meaning: "means; is; because", example: "謎というのは説明できない事柄のことです。", translation: "Mystery means something that cannot be explained.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "というより", meaning: "rather than", example: "今日は涼しいというより寒いくらいだった。", translation: "It was cold rather than cool today.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "といっても", meaning: "although one says", example: "祝日といっても、特に特別なことは無い。", translation: "Although it's a national holiday, there's nothing special.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "とおり", meaning: "in the way; the same as", example: "真理子さんが言ったとおりだった。", translation: "It was exactly as Mariko said.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "ところが", meaning: "however; although", example: "ところが計画は上手くいかなかった。", translation: "However, the plan didn't succeed.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "どころか", meaning: "far from; nevermind", example: "彼はワインどころかビールも飲まない。", translation: "He doesn't even drink beer, let alone wine.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "ところで", meaning: "by the way", example: "ところで、奥さんは元気？", translation: "By the way, how's your wife?", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "としたら", meaning: "if it were the case that; if we assume", example: "明日死ぬとしたら、何がしたいですか。", translation: "If you were going to die tomorrow, what would you want?", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "として", meaning: "as; in the role of", example: "私は留学生として日本に入国しました。", translation: "I entered Japan as an international student.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "としない", meaning: "not try to; not make an effort to", example: "この部屋の中で遊ぶことはしないでください。", translation: "Please try not to play in this room.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "とする", meaning: "try to; be about to", example: "彼は私の質問から逃れようとしていました。", translation: "He tried to avoid answering my question.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "途中に / 途中で", meaning: "on the way; in the middle of", example: "駅に行く道の途中にあります。", translation: "It's on the way to the station.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "と共に", meaning: "together with", example: "彼は妻子と共に旅行に出た。", translation: "He went traveling with his wife and children.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "とは限らない", meaning: "not necessarily so; is not always true", example: "テレビが真実を報道しているとは限らない。", translation: "It's not always the case that the television broadcasts the truth.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "どんなに○○ても", meaning: "no matter how", example: "どんなに食べても彼女は太らない。", translation: "No matter how much she eats, she never gains weight.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "ないことはない", meaning: "can; is not impossible", example: "スキーはできないことはないけど、もう何年もやってないから…", translation: "It's not that I can't ski, it's just I haven't done it in a long time.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "中", meaning: "during; throughout; all over", example: "今電話中です。", translation: "I'm on the phone right now.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "ながら / いながら / ながらも", meaning: "although; despite", example: "彼は毎回遅刻しないと言いながら、遅れています。", translation: "Although he always says he won't be late, he always is.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "なぜなら / なぜかというと", meaning: "because; the reason is", example: "学校を変えた。なぜなら、僕のレベルのクラスがなかったからだ。", translation: "Changed schools because there was no class available at my level.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "なるべく", meaning: "as much as possible", example: "なるべく早く来てください。", translation: "Please come as early as possible.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "なんか / なんて", meaning: "things like; something (casual)", example: "なんか変なもの踏んじゃった。", translation: "I stepped on something strange.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "において / における", meaning: "in; on; at; as for; regarding", example: "日本において国際会議が開かれた。", translation: "An international conference was held in Japan.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "にかけて", meaning: "over (a period); through; concerning", example: "明日は昼から夕方にかけて雨でしょう。", translation: "Tomorrow it will rain from noon through late afternoon.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "にかわって / にかわり", meaning: "instead of; on behalf of", example: "野球にかわり、サッカーがさかんになってきた。", translation: "Soccer has overtaken baseball in popularity.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "に関する / に関して", meaning: "related to; about", example: "生物に関する本を読む。", translation: "I read a book about living things.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "に比べて", meaning: "compared to", example: "前年に比べて利益が上がりました。", translation: "Our profit went up compared to the year before.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "にしては", meaning: "for; considering it's", example: "この子は4才にしては語彙が豊富だ。", translation: "This child has a rich vocabulary for a four-year old.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "にしても", meaning: "even if", example: "冗談にしてもそれは酷過ぎる。", translation: "Even if it's a joke, it's too much.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "に対して", meaning: "regarding; with regards to", example: "彼は誰に対しても優しい。", translation: "With regards to everyone, he is very kind.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "に違いない", meaning: "I'm sure; no doubt that", example: "彼女は日本人に違いない。", translation: "She must be Japanese.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "について", meaning: "concerning; about", example: "私はその事故について証言した。", translation: "I gave testimony about the accident.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "につれて", meaning: "as… then", example: "黒い雲が近づくにつれて、青い空は灰色になった。", translation: "The blue sky turned gray as the dark clouds approached.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "にとって", meaning: "to; for; concerning", example: "私にとって貴重な体験でした。", translation: "It was a valuable experience for me.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "によって / による", meaning: "due to; by means of", example: "この地震による津波の心配はありません。", translation: "There's no worry of a tsunami due to this earthquake.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "によると / によれば", meaning: "according to", example: "天気予報によると明日は晴れです。", translation: "According to the weather forecast, it will be fine tomorrow.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "間 / 間に", meaning: "while; during; between", example: "旅行の間、犬の世話をしてください。", translation: "During my trip, please take care of my dog.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "ば○○ほど", meaning: "the more… the more", example: "この計画は考えば考えるほど気に入りません。", translation: "The more I thought about the plan, the less I liked it.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "ばいい", meaning: "should; can; it'd be good if", example: "明日のデート、何着て行けばいいと思う？", translation: "What clothes should I wear to my date tomorrow?", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "ばかりでなく", meaning: "not only… but also; as well as", example: "おかずばかりでなくご飯も食べなさい。", translation: "Eat the rice, not just the side dishes.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "ばよかった", meaning: "should have; it would have been better if", example: "電話してくれればよかったのに。", translation: "You should've phoned me.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "ふと", meaning: "suddenly; accidentally; unexpectedly", example: "ふと昔の事を思い出したんだ。", translation: "I suddenly remembered the past.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "ふりをする", meaning: "to pretend; to act as if", example: "彼女は聞こえないふりをした。", translation: "She pretended not to hear.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "べき", meaning: "must do; should do", example: "トムはもっと食べるべきだと思う。", translation: "I think Tom should eat more.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "べきではない", meaning: "must not do; should not do", example: "子供の前でそんな話はするべきではない。", translation: "We should not talk about things like that in front of children.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "べつに○○ない", meaning: "not really; not particularly", example: "コーヒーはべつに好きじゃない。", translation: "I don't particularly like coffee.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "ほど", meaning: "the more; to the extent that", example: "今夜は凍えるほど寒い。", translation: "It is cold enough to freeze tonight.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "ほど○○ない", meaning: "is not as… as", example: "死ほど恐ろしいものはない。", translation: "There is nothing scarier than death.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "最中に", meaning: "in the middle of", example: "パーティーの最中に地震があった。", translation: "In the very middle of the party, there was an earthquake.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "まま", meaning: "as it is; leaving as is", example: "このまま時間を止めたい。", translation: "I want to stop time (in this moment).", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "まるで", meaning: "as if; as though", example: "彼のマジックはまるで奇跡です。", translation: "His magic is like a miracle.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "向き", meaning: "towards (direction); suitable for", example: "彼は車を後ろ向きに駐車したの。", translation: "He parked the car backward.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "向け", meaning: "intended for; aimed at", example: "それは少女向けの雑誌です。", translation: "It's a magazine for young girls.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "めったに", meaning: "hardly; rarely; seldom", example: "彼女はめったに怒りません。", translation: "She rarely gets angry.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "もしかしたら", meaning: "perhaps; maybe", example: "もしかしたら来年転勤になるかもしれない。", translation: "It's possible that I might get transferred next year.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "もの", meaning: "because (indicate reason or excuse)", example: "「どうしてパーティーに行かないの。」「だって、忙しいもの。」", translation: "Why don't you come to the party? Because I'm busy.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "ものだ", meaning: "used to do something; should do something", example: "先人の教えには従うものだ。", translation: "We should follow our predecessors' teaching.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "ような気がする", meaning: "have a feeling that; think that", example: "いや、それを避けてきていたような気がする。", translation: "No, I feel as though I had been avoiding it.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "ように 1", meaning: "in order to; so that", example: "迷わないように地図を持って行って。", translation: "Take a map with you so that you don't get lost.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "わけがない", meaning: "there is no way that", example: "あなたのお金をもらえるわけがない！", translation: "I'm not accepting your money!", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "わけだ", meaning: "for that reason; no wonder; as you'd expect", example: "雪が降ってきた。道理で寒いわけだ。", translation: "It's started snowing! No wonder it's so cold.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "わけではない", meaning: "it doesn't mean that; it is not the case", example: "私は彼を故意に傷つけたわけではない。", translation: "I did not hurt him intentionally.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "わけにはいかない", meaning: "must not; can't afford to", example: "彼の悪事を見過ごすわけにはいきません。", translation: "His wrong-doing must not be overlooked.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "わりに", meaning: "for; despite; unexpectedly", example: "私の息子は、歳のわりに大きい。", translation: "My son is big for his age.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "を中心に", meaning: "focused on; centered on", example: "地球は軸を中心に回転します。", translation: "The earth rotates on its axis.", jlptLevel: "N3", source: "JLPT N3" },
  { pattern: "をはじめ / をはじめとする", meaning: "for example; starting with", example: "会議には中国をはじめ、アジアの国々が参加した。", translation: "China and other Asian countries participated in the conference.", jlptLevel: "N3", source: "JLPT N3" },

  // ── JLPT N2 ─────────────────────────────────────────────────────────────
  { pattern: "あるいは", meaning: "or; possibly", example: "紅茶がいいですか、あるいはコーヒーがいいですか。", translation: "Would you like tea or coffee?", jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "いきなり", meaning: "suddenly; all of a sudden", example: "後ろからいきなり肩をたたかれた。", translation: "Someone tapped on my shoulder from behind all of a sudden.", jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "以上 1", meaning: "over; more than", example: "あなたは18歳以上ですか？", translation: "Are you over 18?", jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "以上 2", meaning: "because; now that", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "以上に", meaning: "more than; no less than", example: "気温が30度以上になる。", translation: "The temperature gets above 30 degrees.", jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "いよいよ", meaning: "at last; finally", example: "いよいよ夏休みが始まります。", translation: "Finally, summer vacation is starting.", jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "いわゆる", meaning: "so-called; so to speak", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "上で", meaning: "after (doing something)", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "上に", meaning: "as well; besides; in addition to", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "上は", meaning: "now that; since", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "えない", meaning: "unable to; cannot", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "える / うる", meaning: "can; is possible", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "お○○願う", meaning: "could you please", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "恐れがある", meaning: "there are fears that", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "おまけに", meaning: "to make matters worse; on top of that", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "か○○ないかのうちに", meaning: "right after; as soon as", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "かいがある", meaning: "it's worth one's effort to do something", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "かえって", meaning: "on the contrary; rather; surprisingly", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "限り", meaning: "as long as; while… is the case", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "かと思ったら / かと思うと", meaning: "then again; just when; no sooner than", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "か何か", meaning: "or something", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "かねない", meaning: "might happen; might do something", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "かねる", meaning: "unable to do something", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "かのよう", meaning: "as if; just like", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "から言うと", meaning: "in terms of; from the point of view of", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "からこそ", meaning: "precisely because", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "からして", meaning: "judging from; based on", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "からすると / からすれば", meaning: "judging from; considering", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "からといって", meaning: "just because", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "からには", meaning: "now that; since; so long as", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "から見ると", meaning: "from the point of view of; by the look of", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "気", meaning: "feel like; mood; inclination", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "逆に", meaning: "on the contrary", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "げ", meaning: "giving the appearance of", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "ことから", meaning: "from the fact that", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "ことだから", meaning: "it is exactly because", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "ことなく", meaning: "without doing something even once", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "ごとに", meaning: "each; every; at intervals of", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "ことになっている", meaning: "to be expected to; to be scheduled to", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "ことにはならない", meaning: "just because… doesn't mean…", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "ことは○○が", meaning: "although; but", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "際に", meaning: "at the time; in case of", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "幸い", meaning: "luckily; fortunately", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "さらに", meaning: "furthermore; again; more and more", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "ざるを得ない", meaning: "can't help doing; have no choice but", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "しかも", meaning: "moreover; furthermore", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "次第", meaning: "as soon as", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "次第だ / 次第で", meaning: "depending on; so", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "したがって", meaning: "therefore; accordingly", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "上", meaning: "from the standpoint of", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "少しも○○ない", meaning: "not one bit; not even a little", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "すなわち", meaning: "in other words", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "ずに済む", meaning: "get by without doing something", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "せいぜい", meaning: "at the most; at best", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "せめて", meaning: "at least; at most", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "そういえば", meaning: "come to think of it", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "そうにない", meaning: "extremely unlikely to; showing no signs of", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "その上", meaning: "besides; in addition; furthermore", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "それとも", meaning: "or; or else", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "それなのに", meaning: "and yet; despite this", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "それなら", meaning: "then; if that's the case", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "それにしても", meaning: "nevertheless; even so", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "たあげく", meaning: "to end up; finally (after a long process)", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "だけあって", meaning: "being the case; precisely because", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "だけでなく", meaning: "not only… but also", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "だけに", meaning: "being the case; precisely because; all the more", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "だけのことはある", meaning: "no wonder; it's not surprising that", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "だけは", meaning: "to do all that one can", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "だけまし", meaning: "one should feel grateful for", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "た末 / の末", meaning: "as a conclusion of", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "直ちに", meaning: "at once; immediately", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "だって", meaning: "because; but (casual)", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },
  { pattern: "たって", meaning: "even if; even though; no matter how", example: null, translation: null, jlptLevel: "N2", source: "JLPT N2" },

  // ── JLPT N1 ─────────────────────────────────────────────────────────────
  { pattern: "あえて", meaning: "dare to", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "あくまでも", meaning: "to the end; to the utmost degree", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "案の定", meaning: "just as one thought", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "あらかじめ", meaning: "beforehand; in advance", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "場合によっては", meaning: "depending on the situation", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ばこそ", meaning: "only because", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ばそれまでだ", meaning: "if… then it's over", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "べからず", meaning: "must not; should not (written prohibition)", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "べく", meaning: "in order to; should", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "べくもない", meaning: "cannot; it's not possible", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "びる", meaning: "seeming to be; acting like", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ぶり", meaning: "style; manner; after a long time", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ぶる", meaning: "behaving like; pretending to be", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "だに", meaning: "even (just thinking about it)", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "だの○○だの", meaning: "and; and so forth (listing complaints)", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "であれ○○であれ", meaning: "whether A or B", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "であれ / であろうと", meaning: "whoever / whatever / however", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "でも何でもない", meaning: "not in the least", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "でなくてなんだろう", meaning: "must be; is definitely", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "(で)すら", meaning: "even (emphasis)", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ではあるまいか", meaning: "I wonder if it's not", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ではあるまいし", meaning: "it's not like; it isn't as if", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ではすまない", meaning: "it doesn't end with just", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "どうにも○○ない", meaning: "not … by any means", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "がてら", meaning: "on the same occasion; while doing", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "が早いか", meaning: "as soon as", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "が最後", meaning: "once something occurs; something else happens", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ごとき / ごとく", meaning: "like; as if (literary)", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ぐるみ", meaning: "together with; in its entirety", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "羽目になる", meaning: "to end up with (something unpleasant)", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ひとつ", meaning: "to give something a try", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ほどのことはない", meaning: "not worth; no need to", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ほかに○○ない", meaning: "no other", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ほうがましだ", meaning: "I would rather", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "いかなる", meaning: "any kind of", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "いかんでは / いかんによっては", meaning: "depending on", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "いかんによらず", meaning: "regardless of", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "いかに", meaning: "how; no matter how", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "いかにも", meaning: "indeed; really; truly", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "いまだに", meaning: "still; even now", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "いずれにせよ", meaning: "at any rate; in any case", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "じみた", meaning: "to look like; to resemble", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "限りだ", meaning: "I feel so; extremely", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "かいもなく", meaning: "even though; despite effort", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "か否か", meaning: "whether or not (formal)", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "可能性がある", meaning: "there's a possibility", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "からある", meaning: "as much as; as many as", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "かれ○○かれ", meaning: "or; whether … or", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "かたがた", meaning: "while; for the purpose of", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "かたわら", meaning: "while; at the same time; beside", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "かつて", meaning: "once; before; formerly", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "嫌いがある", meaning: "to have a tendency to", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "きってのは", meaning: "the most … of all", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "きりがない", meaning: "there's no end to", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "極まる / 極まりない", meaning: "extremely", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "極めて", meaning: "extremely; exceedingly", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ことだし", meaning: "because; since", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ことごとく", meaning: "altogether; entirely", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ことなしに", meaning: "without doing something", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ことのないよう", meaning: "so as not to", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "こととて", meaning: "because; since", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "くらいなら", meaning: "rather than", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "くらいのものだ", meaning: "only; the only one who", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "までだ", meaning: "only; all one can do", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "までもない", meaning: "it's not necessary to", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "まじき", meaning: "should not; must not (formal)", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ままに", meaning: "to do as; at the mercy of", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "まみれ", meaning: "to be covered in", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "まるっきり", meaning: "totally; completely", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "めく", meaning: "to show signs of; to look like", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "もはや", meaning: "already; no longer", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "も顧みず / を顧みず", meaning: "regardless of; despite", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "もしないで", meaning: "without even doing", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "もので", meaning: "because; for that reason", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ものを", meaning: "I wish; if only", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ものと思われる", meaning: "to think; to suppose", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ものとして", meaning: "to assume; to suppose", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "もさることながら", meaning: "not only… but also", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "もしくは", meaning: "or; otherwise", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ながらに / ながらの", meaning: "while; during; as it is", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ないではおかない / ずにはおかない", meaning: "will definitely; cannot not", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ないではすまない / ずにはすまない", meaning: "must do; cannot get away without", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ないまでも", meaning: "even if something isn't done", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ないものか", meaning: "can't we…?; can't I…?", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ないものでもない", meaning: "(something) is not entirely impossible", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ないとも限らない", meaning: "might; it's not impossible that", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "なくして", meaning: "without", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "何しろ", meaning: "in any case; as you know", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "なしに", meaning: "without", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ならでは", meaning: "uniquely applying to; only possible with", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ならいざしらず", meaning: "I don't know about A; but B", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "なり", meaning: "as soon as", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "なり○○なり", meaning: "or (choice between options)", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "なりに / なりの", meaning: "in one's own way or style", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "なりとも", meaning: "even a little; at least", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "に値する", meaning: "to be worth; to deserve", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "にあたらない", meaning: "it's not worth; there's no need to", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "にあって", meaning: "at; during; in the condition of", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "にひきかえ", meaning: "in contrast to", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "に至るまで", meaning: "until; as far as", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "に至っては", meaning: "as for; when it comes to", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "に言わせれば", meaning: "if you ask; if one may say", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "にかかっている", meaning: "to depend on", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "にかたくない", meaning: "it's not hard to", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "にまつわる", meaning: "to be related to; surrounding", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "にもほどがある", meaning: "to have a limit; to go too far", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "にもまして", meaning: "more than; above", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "に則って", meaning: "in accordance with", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "に先駆けて", meaning: "to be the first; ahead of", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "にしたって", meaning: "even; even if", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "にして", meaning: "only; in (time span); both", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "に即して", meaning: "in keeping with; in line with", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "にたえる / にたえない", meaning: "can/can't bear to do something", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "に足る / に足りる", meaning: "to be enough; to be worthy of", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "に足りない", meaning: "to be not worth", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "に照らして", meaning: "in comparison with; according to", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "にとどまらず", meaning: "not limited to", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "には及ばない", meaning: "there's no need to; cannot compare to", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "によらず", meaning: "regardless of", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "んばかりに", meaning: "as if; as though; on the verge of", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "んがため", meaning: "in order to (formal)", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "の至り", meaning: "utmost; ultimate", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "の極み", meaning: "utmost; the height of", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "のみか", meaning: "not only… but also", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "のなんのって", meaning: "extremely; so much that", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "を踏まえて", meaning: "based on; taking into account", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "を経て", meaning: "through; after; via", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "をいいことに", meaning: "to take advantage of", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "を限りに", meaning: "starting from; after (this point)", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "を兼ねて", meaning: "also for the purpose of", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "を皮切りに", meaning: "starting with", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "を機に", meaning: "as an opportunity to; taking the chance of", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "を禁じえない", meaning: "can't help but; unable to hold back", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "をものともせず", meaning: "in defiance of; undeterred by", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "をもって 1", meaning: "by means of", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "をもって 2", meaning: "at the time; effective from", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "をおいて", meaning: "other than; without", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "を余儀なくされる", meaning: "to be forced to do something", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "をよそに", meaning: "despite; ignoring", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "思いをする", meaning: "to feel", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "折に", meaning: "when; on the occasion of", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "およそ", meaning: "totally; (not) at all; approximately", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "さもないと", meaning: "otherwise; else; if not so", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "さぞ", meaning: "I'm sure; I'm certain; surely", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "始末だ", meaning: "end up; in the end (negative result)", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "そばから", meaning: "as soon as; right after", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "さも", meaning: "truly; really; as if", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "それなりに", meaning: "as it is; in its own way", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "そうにもない", meaning: "impossible; unlikely", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ただ○○のみだ", meaning: "can do nothing but; only", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "た拍子に", meaning: "the instant; the moment", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ためしがない", meaning: "(something) is never the case", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "たりとも", meaning: "(not) even; (not) any", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "た瞬間に", meaning: "the moment; the instant", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "てっきり", meaning: "surely; certainly (but wrong)", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "たところで", meaning: "even if one does something", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "てからというもの", meaning: "after; since (that time)", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "てかなわない", meaning: "can't stand; unable to bear", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "てまで", meaning: "even; to the point of", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "てみせる", meaning: "I'll definitely; I'll show you", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "てもどうにもならない", meaning: "it's no use", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ても始まらない", meaning: "it's no use", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ても差し支えない", meaning: "can; it's okay if", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "てしかるべきだ", meaning: "should; ought to", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ってば", meaning: "I said; I told you to", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "てやまない", meaning: "always; never stop; sincerely", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "と相まって", meaning: "together with; combined with", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "とあれば", meaning: "if; if it's the case that", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "とあって", meaning: "because of; due to", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "とばかりに", meaning: "as if; as though", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "といえども", meaning: "even; even if; although", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "といい○○といい", meaning: "and; or; both… and…", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "といったらない", meaning: "very; extremely; indescribably", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "というか", meaning: "or; or more precisely", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "というか○○というか", meaning: "(I'm not sure if it's) A or B", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "というところだ / といったところだ", meaning: "approximately; about", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "というもの", meaning: "during a period of time", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "というわけだ", meaning: "this means; that's why", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "というわけではない", meaning: "it's not that; it doesn't mean that", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "といわず", meaning: "not just; both", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ときたら", meaning: "when it comes to; concerning", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ときている", meaning: "because; given that", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ところがある", meaning: "there is; to have a side of", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ところから", meaning: "from the fact that", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "とみられる", meaning: "to be regarded as; to be expected to", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "とみるや", meaning: "at the sight of; upon seeing", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ともなく", meaning: "to do something without thinking about it", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ともなると / ともなれば", meaning: "when; once (something happens)", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ともすれば", meaning: "apt to; prone to", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "と思いきや", meaning: "I thought; but actually", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "とりわけ", meaning: "especially; in particular", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "とされる", meaning: "is considered; is said to be", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "とっさに", meaning: "at once; right away; reflexively", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "としたって / としたところで", meaning: "even if", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "として○○ない", meaning: "not even one", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "とても○○ない", meaning: "cannot possibly", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "とは", meaning: "(indicates word or phrase being defined)", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "とはいえ", meaning: "nonetheless; although; that said", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "とはいうものの", meaning: "having said that; be that as it may", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "つ○○つ", meaning: "(indicates two contrasting actions)", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "はおろか", meaning: "let alone; not to mention", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "はさておき", meaning: "setting aside; apart from", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "や否や", meaning: "the moment that; as soon as", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "やしない", meaning: "not (emphatic negative)", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "(よ)うが / (よ)うと", meaning: "no matter how/what", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "(よ)うが○○まいが / (よ)うと○○まいと", meaning: "whether or not", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "(よ)うか○○まいか", meaning: "whether or not; should I … or not", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "(よ)うものなら", meaning: "if one chooses to (with bad consequence)", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "(よ)うにも○○ない", meaning: "even if one tries to do something, cannot", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ようによっては", meaning: "depending on the way; depending on how", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ゆえに", meaning: "therefore; consequently (formal/literary)", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ざる", meaning: "not; without (classical negative)", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ずじまい", meaning: "never ended up doing", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ずくめ", meaning: "entirely; completely; all", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
  { pattern: "ずとも", meaning: "even without doing", example: null, translation: null, jlptLevel: "N1", source: "JLPT N1" },
];

// ───────────────────────────────────────────────────────────────────────────

async function main() {
  console.log(`[seed] Processing ${JLPT_GRAMMAR.length} JLPT grammar patterns...`);

  let inserted = 0;
  let skipped = 0;

  for (const item of JLPT_GRAMMAR) {
    const existing = await prisma.grammar.findFirst({ where: { pattern: item.pattern } });

    if (existing) {
      skipped++;
    } else {
      await prisma.grammar.create({ data: item });
      inserted++;
    }
  }

  console.log(`[seed] ✓ Done. Inserted: ${inserted}, Skipped (already exists): ${skipped}.`);
}

main()
  .catch((err) => {
    console.error("[seed] Error:", err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
